fix(website): v2
Mine-Treasure/Mine-Treasure-Website pull request #81
Opened 2024-11-22 20:08 UTC by prodbyeagle

- The implementation should be complete, but please review for any potential errors or missing elements.  
- Feedback is welcome to ensure everything works as expected.

2024-11-22 20:10 UTC, prodbyeagle commented
> @prodbyeagle is attempting to deploy a commit to the **Mine Treasure** Team on [Vercel](https://vercel.com).
> 
> A member of the Team first needs to [authorize it](https://vercel.com/git/authorize?team=Mine%20Treasure&type=github&job=%7B%22headInfo%22%3A%7B%22sha%22%3A%226664c45c659b41ec9b0388f003195ee4bc5f8b27%22%7D%2C%22id%22%3A%22QmZYXsWjxCNR2H4ngZpnBJ8pWNRTWaWRCCyRTFQQJUxSUY%22%2C%22org%22%3A%22Mine-Treasure%22%2C%22prId%22%3A81%2C%22repo%22%3A%22Mine-Treasure-Website%22%7D).

oops ? is this my vercel deployment or the production (https://mine-treasure.com/)  one

2024-11-23 11:11 UTC, supercrafter100 commented
Looks like there are conflicting dependencies because its failing to build for the main site preview

2024-11-23 17:26 UTC, supercrafter100 requested changes

2024-11-23 17:26 UTC, supercrafter100 commented on src/components/Footer.tsx
> +                                    >
Would need updating

2024-11-23 17:26 UTC, supercrafter100 commented on src/components/Footer.tsx
> +                                    href="https://github.com/prodbyeagle/minetreasure"
update link

2024-11-23 17:26 UTC, supercrafter100 commented on src/app/api/github/route.ts
> +        });
this needs to be updated to what the existing site uses, because this will break when we migrate this to the main site

2024-11-23 17:26 UTC, supercrafter100 commented on src/app/api/statistics/route.ts
> +        });
Same as above, just copy from the main branch

2024-11-23 17:26 UTC, supercrafter100 commented on src/hooks/useRequest.ts
> +     const [data, setData] = useState<GitHubData | null>(null);
The naming of this file makes no sense anymore. The useRequest hook was a general hook to fetch data from the api but now by the looks of it it has been modified to just fetch the github data from the api? Or at least something like it. Perhaps a refactor or rename makes more sense?

2024-11-23 18:25 UTC, supercrafter100 approved these changes

2024-11-23 18:25 UTC, merged